# Generated by Django 4.0.4 on 2022-05-18 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('variedad', models.CharField(max_length=12)),
                ('size', models.CharField(max_length=10)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('modificado_en', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulbos', to='appProduct.categoria')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appProduct.color')),
            ],
            options={
                'ordering': ['categoria', 'variedad', 'color', 'size'],
            },
        ),
        migrations.AddIndex(
            model_name='bulbo',
            index=models.Index(fields=['codigo'], name='appProduct__codigo_9db700_idx'),
        ),
        migrations.AddIndex(
            model_name='bulbo',
            index=models.Index(fields=['categoria', 'variedad', 'color', 'size'], name='bulbo'),
        ),
        migrations.AddConstraint(
            model_name='bulbo',
            constraint=models.UniqueConstraint(fields=('categoria', 'variedad', 'color', 'size'), name='articulo'),
        ),
    ]
