# Generated by Django 4.0.4 on 2022-05-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProduct', '0002_bulbo_bulbo_appproduct__codigo_9db700_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulbo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
