# Generated by Django 4.0.4 on 2022-05-13 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('rut', models.IntegerField(default=0)),
                ('dv', models.CharField(max_length=1)),
                ('direccion', models.CharField(max_length=40)),
                ('comuna', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=15)),
                ('pais', models.CharField(max_length=15)),
                ('fono', models.IntegerField(default=0)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('modificado_en', models.DateField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
